sudo: required

env:
  - WORKSPACE='/project'

services:
  - docker

language: bash

before_install:
  - sudo docker pull knowshan/centos6-mkrpm
  - gem install package_cloud

install:
  - sudo docker run -d -it -e WORKSPACE="${WORKSPACE}" -e TRAVIS_REPO_SLUG="${TRAVIS_REPO_SLUG}" -e TRAVIS_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}" -v $PWD:"${WORKSPACE}" --name centos6 knowshan/centos6-mkrpm

script:
  - sudo docker exec centos6 "$WORKSPACE"/mkrpm.sh
  - file build_"${TRAVIS_BUILD_NUMBER}"/*.rpm

after_success:
  - package_cloud push knowshan/ec2/el/6 build_"${TRAVIS_BUILD_NUMBER}"/*.rpm

after_script:
  - sudo docker stop centos6

